config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get 'pages/about'
  post '/', :controller => 'pages', :action => 'create'

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  VALID_NAME_REGEX = /\A[A-Z]+[a-z' ]{2,}+[A-Z][a-z']{1,}+\z/
  # регулярное выражение пропускает только два слова разделенных пробелом
  # оба слова должны начинаться с большой буквы, и иметь:
  # Имя:      2+ буквы
  # Фамилия:  2+ буквы

  validates :name,      presence: true, format:     { with: VALID_NAME_REGEX }
  validates :email,     presence: true, format:     { with: VALID_EMAIL_REGEX }
  validates :age,       inclusion:  { within: 17..65, message: "is invalid: you must be from 17 to 65 years old" }
  validates :datetime,  presence: true
  # paperclip validations
  has_attached_file    :attachment
  validates_attachment :attachment,
                       :content_type => {:content_type => %w(image/jpeg
                                                             image/jpg
                                                             image/png
                                                             application/pdf
                                                             application/msword
                                                             application/vnd.openxmlformats-officedocument.wordprocessingml.document)
                                        }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @feedback = Feedback.new
  end

  def about
  end

  def create
    @feedback = Feedback.new(feedback_params)
    if @feedback.save
      @datetime = feedback_params[:datetime]
      render 'thanks'
    else
      render 'home'
    end
  end

  private

  def feedback_params
    params.require(:feedback).permit(:name, :email, :age, :datetime, :message, :attachment)
  end
end

#TODO: client-side validation

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MassMedia Group Task</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top navbar-custom">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">MassMedia Group</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", pages_about_path %></li>
      </ul>
    </div>
  </div>
</nav>
<div>
  <%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
<h1>About this app</h1>
  <h4>
    <p>This is my interview task application for "MassMedia Group" company based in Khmelnytskyi, Ukraine.</p>
  </h4>
</div>

app/views/pages/home.html.erb
<script type="text/javascript">
  $(function() {
    // подключаю datetimepicker
    $('#datetimepicker').datetimepicker();
  });
</script>

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
  <h1>Here you can leave your feedback!</h1>
  <p>For additional information visit <%= link_to "About", pages_about_path %> page</p>
  <hr />
  <div class="row distance-before-footer">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <%= form_for :feedbacks do |feedback| %>
        <%= render 'shared/error_messages' %>
        <div class=	"col-lg-5 col-md-5 col-sm-5 col-xs-5">
          <%= feedback.label :name %><br />
          <%= feedback.text_field :name, class: 'form-control', placeholder: "Type here your name" %>
          <br />
          <%= feedback.label :email %><br />
          <%= feedback.text_field :email, class: 'form-control', placeholder: "Your e-mail" %>
          <br/>
          <%= feedback.label :age %><br />
          <%= feedback.text_field :age, class: 'form-control', placeholder: "Your age" %>
          <br />
          <%= feedback.label :datetime %><br />
          <%= feedback.text_field :datetime, id: 'datetimepicker', class: 'form-control', placeholder: "Select date & time" %>
          <br />
          <%= feedback.submit "Submit feedback", class: 'btn btn-default btn-lg btn-success'%>
        </div>
        <div class=	"col-lg-7 col-md-7 col-sm-7 col-xs-7">
          <%= feedback.label :message %><br/>
          <%= feedback.text_area :message, class: 'form-control', rows: 9, placeholder: "Leave here your message..."%>
          <br />
          <%= feedback.label :attachment %><br />
          <%= feedback.file_field :attachment, as: :file %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/thanks.html.erb
<div class = "col-lg-12 col-md-12 col-sm-12 col-xs-12">
  <h2>Thank you!</h2>
  <h4>We are waiting for you <%= @datetime %></h4>
  <h4><%= link_to "I'm understand that, let me back now!", root_path %></h4>
</div>

app/views/shared/_error_messages.html.erb
<% if @feedback.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <% @feedback.errors.full_messages.each do |msg| %>
            <span class="glyphicon glyphicon-remove"></span> <%= msg %><br/>
        <% end %>
      </div>
    </div>
<% end %>